In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
import tensorflow as tf
from sklearn.metrics import mean_squared_error

ValueError: Name tf.RaggedTensorSpec has already been registered for class tensorflow.python.ops.ragged.ragged_tensor.RaggedTensorSpec.

In [ ]:
df = pd.DataFrame(data=[
    [2],
    [4],
    [6],
    [8],
    [10],
    [12],
    [14],
    [16],
    [18],
    [20],
], columns=['y'])

In [ ]:
#df['y_t-1'] = df['y'].shift(1)
#df['y_t-2'] = df['y'].shift(2)

In [ ]:
#df = df[df.columns[::-1]]

In [33]:
train_size = int(len(df) * 0.8)
df_train, df_test = df[:train_size], df[train_size:]
scaler = MinMaxScaler()
df_train = scaler.fit_transform(df_train)
df_test  = scaler.transform(df_test)

In [34]:
X_train = df_train[:, :-1]
y_train = df_train[:, -1]
X_test = df_test[:, :-1]
y_test = df_test[:, -1]


In [35]:
X_train

array([[0.        ,        nan],
       [0.14285714, 0.        ],
       [0.28571429, 0.16666667],
       [0.42857143, 0.33333333],
       [0.57142857, 0.5       ],
       [0.71428571, 0.66666667],
       [0.85714286, 0.83333333],
       [1.        , 1.        ]])

In [31]:
X_train

array([[0.        ,        nan,        nan],
       [0.14285714, 0.        ,        nan],
       [0.28571429, 0.16666667, 0.        ],
       [0.42857143, 0.33333333, 0.2       ],
       [0.57142857, 0.5       , 0.4       ],
       [0.71428571, 0.66666667, 0.6       ],
       [0.85714286, 0.83333333, 0.8       ],
       [1.        , 1.        , 1.        ]])

In [ ]:
look_back = 1
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2)



In [33]:
# Editable DataFrame creation - you can modify this
# Create datetime index with 1-second periods starting from current time
datetime_index = pd.date_range(start='2025-07-28 10:00:00', periods=12, freq='1s')

# Create DataFrame with numbers 1-12 and datetime index
df = pd.DataFrame({'A': [1,2,3,4,5,6,7,8,9,10,11,12]}, index=datetime_index)
window_size = 3


In [34]:
#Opcion automatica, no realiza copia de datos. Tiene alguna restriccion?
np.lib.stride_tricks.sliding_window_view(df["A"], window_size)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12]], dtype=int64)

In [25]:
X = np.column_stack([df["A"].shift(i) for i in range(window_size)])


In [27]:
X = X[window_size - 1:]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices